### ISSUE TITLE
[Bug]: Midori (v11.6) disables all extensions at start

### ISSUE THREAD

**Issue by yangliu2025** [goastian/midori-desktop#134]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have tried to create a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Midori (v11.6) disables all extensions at start. They are not displayed in the top right extension bar. In the extension management page, the enabled extensions are displayed as if they are at enabled status. But in fact they doesn't work at all. I need to click the enable/disable switch twice. Then the clicked extension display in the extension bar and ask if it need to be enabled in private mode. And then they works for web pages opened later.

### Reproduction Steps

1. install Midori v11.6
2. start Midori and install any extension (for example, ad block) and enable it.
3. close Midori.
4. start Midori.
5. you shall find the extension is NOT shown in the extension bar.
6. enter the extension management page, the extension may be shown as enabled, or disabled. 
7. If it's shown enabled, disable it.
8. enable it. It shall display in the extension bar.
9. open any webpage to check if the extension works.

### Expected Behavior

All enabled extensions shall display correctly in the extension bar when Midori starts. And they shall function normally.

### Actual Behavior

All enabled extensions are disabled. You have to enter extension management UI to reenable them one by one.

### Screenshots
When I close Midori, it looks like this:
<img width="291" height="40" alt="Image" src="https://github.com/user-attachments/assets/045439fa-981f-4f30-9c78-49d171a6afcd" />

When I start Midori again, the extensions disappear:
<img width="291" height="40" alt="Image" src="https://github.com/user-attachments/assets/1f1c5656-0860-43f0-b009-7fd5ba3d05da" />

But in the extension management page, they are shown as enabled, but in fact they don't work:
<img width="1013" height="375" alt="Image" src="https://github.com/user-attachments/assets/7a76421f-1943-4649-931f-54cef9abca89" />

### Browser Version

11.6

### Operating System

Ubuntu 24.04

**Comment by Lightning-** [comment]
I have a similar issue running Slackware. Tried to update from 11.5.1 using the [precompiled release tarball](https://github.com/goastian/midori-desktop/releases/download/v11.6/midori-11.6.linux-x86_64.tar.bz2).  
Main difference (for me) is that, after reactivation of the extensions, they're just activated in the window where the reactivation happened and in each new window they're gone again.  
Also wanna add that the extension's hotkeys and settings are preserved and after reactivation everything works as expected (at least in this one browser window).

**Comment by Ponchale** [comment]
This issue has been resolved in version 11.6.1.

**Comment by gmpakpak12** [comment]
> This issue has been resolved in version 11.6.1.

where is 11.6.1 for windows 11? im on 11.6 and it does this one too

**Comment by luisfer153** [comment]
I update from 11.6 to 11.6.1 and the bug persist, and not its only the extensions, the themes also restart. i need to apply the configuration each time the browser restart as @Lightning- says.

edit: sorry i was confused  the binary says 11.6-1  

### operating system
- Linux Mint 22.1 x86_64

**Comment by Ponchale** [comment]
> I update from 11.6 to 11.6.1 and the bug persist, and not its only the extensions, the themes also restart. i need to apply the configuration each time the browser restart as [@Lightning-](https://github.com/Lightning-) says.
> ### operating system
> 
>     * Linux Mint 22.1 x86_64

Version 11.6.1 not yet available is in development but this issue is now fixed
