### ISSUE TITLE
[Bug]: Scrollbar appears whenever mouse hovers over tab bar in vertical view

### ISSUE THREAD

**Issue by diinrel** [goastian/midori-desktop#94]
### Pre-Submission Checklist

- [ ] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [ ] I am using the latest supported version of the browser.
- [ ] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have tried to create a new profile and the issue still occurs.
- [ ] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [ ] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

Whenever the mouse hovers over the vertical tab bar, a scroll bar appears and shifts the edge of the tabs over. This occurs regardless of how many tabs are present. Once the mouse is no longer over the tab bar, the scroll bar disappears.

### Reproduction Steps

Set tab bar to "vertical".
Hover mouse over tab bar
Scroll bar appears even when not needed

### Expected Behavior

There should be no scroll bar unless there are more tabs than can fit into the current view

### Actual Behavior

Scroll bar appears whenever -- and only when -- the mouse is hovering over it. This has been the case on all versions since 11.3.3.

### Screenshots

https://github.com/user-attachments/assets/961abc1f-63a1-488e-a6e3-0531ad7a078e

### Browser Version

> 11.3.3.

### Operating System

Windows 10 (3 different PCs)

**Comment by Ponchale** [comment]
This problem is already fixed in version 11.5, please we recommend updating to the new version.

**Comment by diinrel** [comment]
Hi, thanks for the response. This is in fact still an issue on 11.5, on all 3 Windows 10 computers I've installed it on. It's been an issue on 11.4, 11.4.3 and now 1.5

It worked fine on 11.3.3

(I have fixed my initial post to clarify the versions affected)

**Comment by Ponchale** [comment]
We'll be improving this in the next few releases as we're redesigning that feature.
